import os
DEBUG = True
S_SYSTEM_VERSION = 'V1.0 - WaveAssistEngineDocker'
LOG_NUMBER = 10
CWD_PATH = os.getcwd()
PROJECT_LOGS_PATH = os.path.join(CWD_PATH, 'Logs','project_logs.log')
BASE_URL = "https://assistapi.wavepredict.com"
TIMEOUT_DURATION = 300
INTEGRATION_SUFFIX = "_integrations"

##Keys:
PD_DATA_KEY = 'PDData'
IO_DATA_KEY = 'IODataKey'
DATA_KEY = "DATA"
DB_NAME = "WaveAssist"
CONNECTION_STRING = os.getenv('MONGODB_CONNECTION_STRING', 'REMOVED_CREDENTIAL')
STRING = os.getenv('MONGODB_CONNECTION_STRING', 'REMOVED_CREDENTIAL')


##Integrations
INTEGRATIONS_SUFFIX_KEY = "_integrations"

AWSS3_ACCESS_KEY_VALUE = os.getenv('AWS_ACCESS_KEY_ID','')
AWSS3_SECRET_KEY_VALUE = os.getenv('AWS_SECRET_ACCESS_KEY','')
ZERODHA_API_KEY_VALUE = os.getenv('ZERODHA_API_KEY','')
ZERODHA_API_SECRET_KEY_VALUE = os.getenv('ZERODHA_API_SECRET','')


MAILER_FROM_EMAIL_ADDRESS = os.getenv('MAILER_FROM_EMAIL_ADDRESS', '')
MAILER_LOGIN_EMAIL = os.getenv('MAILER_LOGIN_EMAIL', '')
MAILER_LOGIN_EMAIL_PASSWORD = os.getenv('MAILER_LOGIN_EMAIL_PASSWORD', '')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
