# Generated by Django 4.2 on 2023-07-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('firebase_uid', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'WaveAssist_Client',
            },
        ),
        migrations.CreateModel(
            name='IOData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('type', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'WaveAssist_IOData',
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('start_frequency_in_seconds', models.IntegerField(default=0)),
                ('python_code', models.TextField(default='')),
                ('running_status', models.IntegerField(default=0)),
                ('server_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data_list', models.ManyToManyField(related_name='input_data_list', to='WaveAssistApiApp.iodata')),
                ('output_data_list', models.ManyToManyField(related_name='output_data_list', to='WaveAssistApiApp.iodata')),
            ],
            options={
                'db_table': 'WaveAssist_Nodes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.client')),
                ('node_list', models.ManyToManyField(to='WaveAssistApiApp.nodes')),
            ],
            options={
                'db_table': 'WaveAssist_Project',
            },
        ),
        migrations.AddField(
            model_name='iodata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project'),
        ),
    ]
