# Generated by Django 4.2 on 2024-05-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('should_show_in_output', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DataKey',
                'verbose_name_plural': 'DataKeys',
                'db_table': 'WaveAssist_DataKey',
            },
        ),
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('integration_key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('import_code', models.TextField(default='')),
                ('function_code', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'db_table': 'WaveAssist_Integrations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(default='', max_length=255, null=True)),
                ('firebase_uid', models.CharField(max_length=100, unique=True)),
                ('can_create_projects', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'WaveAssist_User',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_key', models.CharField(max_length=255, unique=True)),
                ('running_status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('refresh_status', models.IntegerField(default=0)),
                ('memory_allocated_in_mb', models.IntegerField(default=512)),
                ('cpu_allocated_in_vcpu', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration_array', models.ManyToManyField(blank=True, to='WaveAssistApiApp.integrations')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'WaveAssist_Project',
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_key', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('python_code', models.TextField(default='')),
                ('run_type', models.IntegerField(default=0)),
                ('schedule_object', models.TextField(default='', null=True)),
                ('test_status', models.IntegerField(default=0)),
                ('test_output', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data_key_array', models.ManyToManyField(blank=True, related_name='input_data_array', to='WaveAssistApiApp.datakey')),
                ('output_data_key_array', models.ManyToManyField(blank=True, related_name='output_data_array', to='WaveAssistApiApp.datakey')),
                ('project_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project')),
                ('run_after_nodes_array', models.ManyToManyField(blank=True, to='WaveAssistApiApp.nodes')),
            ],
            options={
                'verbose_name': 'Nodes',
                'verbose_name_plural': 'Nodes',
                'db_table': 'WaveAssist_Nodes',
            },
        ),
        migrations.CreateModel(
            name='DataRuns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_run_key', models.CharField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project')),
            ],
            options={
                'verbose_name': 'Flows',
                'verbose_name_plural': 'Flows',
                'db_table': 'WaveAssist_Flows',
            },
        ),
        migrations.AddField(
            model_name='datakey',
            name='project_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project'),
        ),
        migrations.CreateModel(
            name='DashboardSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dashboard_section_key', models.CharField(max_length=255, null=True, unique=True)),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('display_type', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('should_display_title', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_key_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.datakey')),
                ('project_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project')),
            ],
            options={
                'verbose_name': 'DashboardSection',
                'verbose_name_plural': 'DashboardSection',
                'db_table': 'WaveAssist_DashboardSection',
            },
        ),
        migrations.CreateModel(
            name='AccessProvided',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('project_access_type', models.IntegerField(default=0)),
                ('data_run_access_type', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_run_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.dataruns')),
                ('project_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.user')),
            ],
            options={
                'verbose_name': 'AccessProvided',
                'verbose_name_plural': 'AccessProvided',
                'db_table': 'WaveAssist_AccessProvided',
            },
        ),
    ]
