# Generated by Django 4.2 on 2024-06-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('WaveAssistApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dag_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interval_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.intervalschedule')),
            ],
            options={
                'verbose_name': 'DAG',
                'verbose_name_plural': 'DAGs',
                'db_table': 'WaveAssist_DAG',
            },
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='run_type',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='schedule_object',
        ),
        migrations.AddField(
            model_name='nodes',
            name='interval_object',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='is_starting_node',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DAGRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dag_run_key', models.CharField(max_length=255, unique=True)),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dag_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.dag')),
                ('data_run_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.dataruns')),
                ('periodic_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'DAGRun',
                'verbose_name_plural': 'DAGRuns',
                'db_table': 'WaveAssist_DAGRun',
            },
        ),
        migrations.AddField(
            model_name='dag',
            name='node_array',
            field=models.ManyToManyField(blank=True, to='WaveAssistApiApp.nodes'),
        ),
        migrations.AddField(
            model_name='dag',
            name='project_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project'),
        ),
        migrations.AddField(
            model_name='dag',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='WaveAssistApiApp.nodes'),
        ),
    ]
