# Generated by Django 4.2 on 2023-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creation_status',
            new_name='running_status',
        ),
        migrations.AddField(
            model_name='nodes',
            name='node_key',
            field=models.CharField(default='hello', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_key',
            field=models.CharField(default='hello', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
