# Generated by Django 4.2 on 2023-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0002_rename_creation_status_project_running_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='input_data_list',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='output_data_list',
        ),
        migrations.AddField(
            model_name='iodata',
            name='output_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodes',
            name='input_data_array',
            field=models.ManyToManyField(related_name='input_data_array', to='WaveAssistApiApp.iodata'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='output_data_array',
            field=models.ManyToManyField(related_name='output_data_array', to='WaveAssistApiApp.iodata'),
        ),
    ]
