# Generated by Django 4.2 on 2024-06-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0002_dag_remove_nodes_run_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataruns',
            old_name='project',
            new_name='project_object',
        ),
    ]
