# Generated by Django 4.2 on 2023-07-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0003_remove_nodes_input_data_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='iodata',
            options={'verbose_name': 'IOData', 'verbose_name_plural': 'IOData'},
        ),
        migrations.AlterModelOptions(
            name='nodes',
            options={'verbose_name': 'Nodes', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='node_list',
        ),
        migrations.AddField(
            model_name='project',
            name='node_array',
            field=models.ManyToManyField(blank=True, to='WaveAssistApiApp.nodes'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='input_data_array',
            field=models.ManyToManyField(blank=True, related_name='input_data_array', to='WaveAssistApiApp.iodata'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='output_data_array',
            field=models.ManyToManyField(blank=True, related_name='output_data_array', to='WaveAssistApiApp.iodata'),
        ),
    ]
