# Generated by Django 4.2 on 2024-06-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('WaveAssistApiApp', '0003_rename_project_dataruns_project_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='interval_object',
        ),
        migrations.AddField(
            model_name='nodes',
            name='crontab_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='interval_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='schedule_type',
            field=models.CharField(choices=[('none', 'none'), ('interval', 'interval'), ('crontab', 'crontab')], default='interval', max_length=10),
        ),
    ]
