# Generated by Django 4.2 on 2023-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0004_alter_client_options_alter_iodata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iodata',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
