# Generated by Django 4.2 on 2024-06-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0004_remove_nodes_interval_object_nodes_crontab_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dag',
            old_name='interval_object',
            new_name='interval_schedule',
        ),
    ]
