# Generated by Django 4.2 on 2023-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0005_iodata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='iodata',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
