# Generated by Django 4.2 on 2024-06-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0005_rename_interval_object_dag_interval_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dag',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dagrun',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dag',
            name='dag_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dagrun',
            name='dag_run_key',
            field=models.CharField(max_length=255),
        ),
    ]
