# Generated by Django 4.2 on 2023-07-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0006_iodata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iodata',
            old_name='type',
            new_name='action_type',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='server_status',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='type',
        ),
    ]
