# Generated by Django 4.2 on 2024-06-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0006_dag_is_enabled_dagrun_is_enabled_alter_dag_dag_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataruns',
            old_name='is_active',
            new_name='is_enabled',
        ),
    ]
