# Generated by Django 4.2 on 2024-06-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0007_rename_is_active_dataruns_is_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataruns',
            options={'verbose_name': 'DataRun', 'verbose_name_plural': 'DataRuns'},
        ),
        migrations.AlterModelTable(
            name='dataruns',
            table='WaveAssist_DataRuns',
        ),
    ]
