# Generated by Django 4.2 on 2023-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0007_rename_type_iodata_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='refresh_status',
            field=models.IntegerField(default=0),
        ),
    ]
