# Generated by Django 4.2 on 2023-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0008_project_refresh_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='client_array',
            field=models.ManyToManyField(blank=True, to='WaveAssistApiApp.client'),
        ),
    ]
