# Generated by Django 4.2 on 2024-06-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0009_remove_user_firebase_uid_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cpu_allocated_in_vcpu',
        ),
        migrations.RemoveField(
            model_name='project',
            name='memory_allocated_in_mb',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='refresh_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='running_status',
        ),
    ]
