# Generated by Django 4.2 on 2023-08-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0009_remove_project_client_project_client_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('import_code', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Integrations',
                'verbose_name_plural': 'Integrations',
                'db_table': 'WaveAssist_Integrations',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='integration_array',
            field=models.ManyToManyField(blank=True, to='WaveAssistApiApp.integrations'),
        ),
    ]
