# Generated by Django 4.2 on 2024-06-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0010_remove_project_cpu_allocated_in_vcpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datakey',
            name='should_show_in_output',
        ),
    ]
