# Generated by Django 4.2 on 2023-08-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0010_integrations_project_integration_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrations',
            name='function_code',
            field=models.TextField(default=''),
        ),
    ]
