# Generated by Django 4.2 on 2024-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0011_remove_datakey_should_show_in_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprovided',
            name='dashboard_access_type',
            field=models.IntegerField(default=0),
        ),
    ]
