# Generated by Django 4.2 on 2023-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0011_integrations_function_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='test_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='nodes',
            name='test_status',
            field=models.IntegerField(default=0),
        ),
    ]
