# Generated by Django 4.2 on 2024-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0012_accessprovided_dashboard_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
