# Generated by Django 4.2 on 2023-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0012_nodes_test_output_nodes_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='cpu_allocated_in_vcpu',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='nodes',
            name='memory_allocated_in_mb',
            field=models.IntegerField(default=512),
        ),
    ]
