# Generated by Django 4.2 on 2024-07-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0013_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
