# Generated by Django 4.2 on 2023-10-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0013_nodes_cpu_allocated_in_vcpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='cpu_allocated_in_vcpu',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='memory_allocated_in_mb',
        ),
        migrations.AddField(
            model_name='project',
            name='cpu_allocated_in_vcpu',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='project',
            name='memory_allocated_in_mb',
            field=models.IntegerField(default=512),
        ),
    ]
