# Generated by Django 4.2 on 2024-07-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0014_nodes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedRuns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, null=True, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=100)),
                ('is_running', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_run_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.dataruns')),
                ('project_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='dagrun',
            name='dag_object',
        ),
        migrations.RemoveField(
            model_name='dagrun',
            name='data_run_object',
        ),
        migrations.RemoveField(
            model_name='dagrun',
            name='periodic_task',
        ),
        migrations.DeleteModel(
            name='DAG',
        ),
        migrations.DeleteModel(
            name='DAGRun',
        ),
    ]
