# Generated by Django 4.2 on 2024-02-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0014_remove_nodes_cpu_allocated_in_vcpu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('running_status', models.IntegerField(default=0)),
                ('refresh_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_array', models.ManyToManyField(blank=True, to='WaveAssistApiApp.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project')),
            ],
            options={
                'verbose_name': 'Flows',
                'verbose_name_plural': 'Flows',
                'db_table': 'WaveAssist_Flows',
            },
        ),
    ]
