# Generated by Django 4.2 on 2024-07-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('WaveAssistApiApp', '0015_publishedruns_remove_dagrun_dag_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, null=True, unique=True)),
                ('is_running', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interval_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.intervalschedule')),
                ('node_array', models.ManyToManyField(blank=True, to='WaveAssistApiApp.nodes')),
                ('parent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.publishedruns')),
                ('periodic_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='WaveAssistApiApp.nodes')),
            ],
            options={
                'verbose_name': 'DAG',
                'verbose_name_plural': 'DAGs',
                'db_table': 'WaveAssist_DAG',
            },
        ),
    ]
