# Generated by Django 4.2 on 2024-02-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0015_flows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_key',
        ),
    ]
