# Generated by Django 4.2 on 2024-07-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0016_dag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dag',
            name='start_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_node', to='WaveAssistApiApp.nodes'),
        ),
    ]
