# Generated by Django 4.2 on 2024-07-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0017_alter_dag_start_node'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishedRuns',
            new_name='Deployments',
        ),
        migrations.RenameField(
            model_name='dag',
            old_name='parent_run',
            new_name='parent_deployment',
        ),
    ]
