# Generated by Django 4.2 on 2024-07-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0018_rename_publishedruns_deployments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployments',
            options={'verbose_name': 'Deployment', 'verbose_name_plural': 'Deployments'},
        ),
        migrations.AlterModelTable(
            name='deployments',
            table='WaveAssist_Deployments',
        ),
    ]
