# Generated by Django 4.1.13 on 2024-07-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('WaveAssistApiApp', '0019_alter_deployments_options_alter_deployments_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='test_output',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='test_status',
        ),
        migrations.AddField(
            model_name='dag',
            name='crontab_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule'),
        ),
        migrations.AlterField(
            model_name='dag',
            name='parent_deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.deployments'),
        ),
    ]
