# Generated by Django 4.2 on 2025-01-22 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "WaveAssistApiApp",
            "0020_remove_nodes_test_output_remove_nodes_test_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_name",
                    models.CharField(default="", max_length=255, null=True),
                ),
                ("account_uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "plan_name",
                    models.CharField(default="free", max_length=255, null=True),
                ),
                (
                    "mongo_db_url",
                    models.CharField(default="", max_length=255, null=True),
                ),
                (
                    "rabbitmq_url",
                    models.CharField(default="", max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WaveAssistApiApp.user",
                    ),
                ),
            ],
        ),
    ]
