# Generated by Django 4.2 on 2025-01-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0021_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="db_name",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
