# Generated by Django 4.2 on 2025-01-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0022_account_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rabbitmq_queue',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
