# Generated by Django 4.2 on 2025-01-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0022_account_db_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.AlterModelTable(
            name="account",
            table="WaveAssist_Account",
        ),
    ]
