# Generated by Django 4.2 on 2025-01-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0024_account_rabbitmq_queue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='rabbitmq_queue',
            new_name='celery_queue',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rabbitmq_url',
        ),
    ]
