# Generated by Django 4.2 on 2025-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "WaveAssistApiApp",
            "0025_rename_rabbitmq_queue_account_celery_queue_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="pip_requirements_array_json",
            field=models.TextField(default="[]"),
        ),
    ]
