# Generated by Django 4.2 on 2025-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0026_account_pip_requirements_array_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
