# Generated by Django 4.2 on 2025-02-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0028_alter_account_account_uid_alter_user_firebase_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='worker_arn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
