# Generated by Django 4.2 on 2025-02-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0029_account_worker_arn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='worker_arn',
            new_name='worker_service_arn',
        ),
    ]
