# Generated by Django 4.2 on 2025-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0030_rename_worker_arn_account_worker_service_arn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "template_key",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("name", models.CharField(default="", max_length=255, null=True)),
                ("description", models.TextField(default="")),
                ("repo_url", models.CharField(default="", max_length=255, null=True)),
                ("tags", models.CharField(default="", max_length=255, null=True)),
                ("deployment_script", models.TextField(default="")),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Templates",
                "verbose_name_plural": "Templates",
                "db_table": "WaveAssist_Templates",
            },
        ),
    ]
