# Generated by Django 4.2 on 2025-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0031_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="repo_name",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="template_readme",
            field=models.TextField(default=""),
        ),
    ]
