# Generated by Django 4.2 on 2025-05-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0032_template_repo_name_template_template_readme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Template",
        ),
    ]
