# Generated by Django 4.2 on 2025-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0033_delete_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_working_running',
            field=models.BooleanField(default=True),
        ),
    ]
