# Generated by Django 4.2 on 2025-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0034_account_is_working_running"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodes",
            name="node_key",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_key",
            field=models.CharField(max_length=255),
        ),
    ]
