# Generated by Django 4.2 on 2025-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0036_alter_dataruns_data_run_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
