# Generated by Django 4.2 on 2025-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0037_alter_project_project_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataruns",
            name="data_run_key",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
