# Generated by Django 4.2 on 2025-06-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0038_alter_dataruns_data_run_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DagRuns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=60, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dag_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.dag')),
                ('data_run_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.dataruns')),
                ('project_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.project')),
            ],
            options={
                'verbose_name': 'DAG Run',
                'verbose_name_plural': 'DAG Runs',
                'db_table': 'WaveAssist_DagRuns',
            },
        ),
        migrations.CreateModel(
            name='NodeRuns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('RETRY', 'Retry'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dag_run_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.dagruns')),
                ('node_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.nodes')),
            ],
            options={
                'verbose_name': 'Node Run',
                'verbose_name_plural': 'Node Runs',
                'db_table': 'WaveAssist_NodeRuns',
            },
        ),
    ]
