# Generated by Django 4.2 on 2025-06-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0039_dagruns_noderuns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dagruns',
            name='status',
        ),
        migrations.AlterField(
            model_name='noderuns',
            name='task_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
