# Generated by Django 4.2 on 2025-06-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0040_remove_dagruns_status_alter_noderuns_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='node_key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
