# Generated by Django 4.2 on 2025-06-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0041_alter_nodes_node_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dagruns',
            name='dag_object',
        ),
    ]
