# Generated by Django 4.2 on 2025-06-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0043_remove_noderuns_result_remove_noderuns_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dagruns',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='dagruns',
            name='finished_at',
        ),
    ]
