# Generated by Django 4.2 on 2025-06-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0044_rename_started_at_dagruns_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='open_router_key',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
