# Generated by Django 4.2 on 2025-07-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0045_account_open_router_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
