# Generated by Django 4.2 on 2025-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0046_account_is_premium_project_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_key',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
