# Generated by Django 4.2 on 2025-08-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0047_project_template_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('assistant_key', models.CharField(max_length=255, unique=True)),
                ('github_url', models.CharField(default='', max_length=255, null=True)),
                ('credits_needed_per_unit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assistant',
                'verbose_name_plural': 'Assistants',
                'db_table': 'WaveAssist_Assistants',
            },
        ),
    ]
