# Generated by Django 4.2 on 2025-08-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0048_assistants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistants',
            name='credits_needed_per_unit',
            field=models.FloatField(default=0.0),
        ),
    ]
