# Generated by Django 4.2 on 2025-08-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0050_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credits_in_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
