# Generated by Django 4.2 on 2025-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0051_payment_credits_in_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credits_granted',
            field=models.BooleanField(default=False),
        ),
    ]
