# Generated by Django 4.2 on 2025-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0052_payment_credits_granted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="plan_name",
            field=models.CharField(default="operator", max_length=255, null=True),
        ),
    ]
