# Generated by Django 4.2 on 2025-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0053_alter_account_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('auth_url', models.CharField(max_length=500)),
                ('token_url', models.CharField(max_length=500)),
                ('refresh_url', models.CharField(blank=True, max_length=500, null=True)),
                ('default_scopes', models.JSONField(default=list)),
                ('default_grant_type', models.CharField(default='authorization_code', max_length=20)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('resource_configs', models.JSONField(default=dict)),
                ('base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'WaveAssist_Provider',
            },
        ),
    ]
