# Generated by Django 4.2 on 2026-02-23 10:59

from django.db import migrations, connection, models

TABLE = "WaveAssist_Provider"


def get_existing_columns(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s
            """,
            [TABLE],
        )
        return {row[0] for row in cursor.fetchall()}


def add_missing_columns(apps, schema_editor):
    existing = get_existing_columns(apps, schema_editor)
    with connection.cursor() as cursor:
        if "extra_auth_params" not in existing:
            cursor.execute(
                "ALTER TABLE WaveAssist_Provider ADD COLUMN extra_auth_params JSON NULL"
            )
        if "extra_token_params" not in existing:
            cursor.execute(
                "ALTER TABLE WaveAssist_Provider ADD COLUMN extra_token_params JSON NULL"
            )
        if "token_endpoint_auth_method" not in existing:
            cursor.execute(
                "ALTER TABLE WaveAssist_Provider ADD COLUMN token_endpoint_auth_method VARCHAR(50) NOT NULL DEFAULT 'client_secret_basic'"
            )
        if "token_fetch_method" not in existing:
            # Add as nullable first to avoid MySQL 1067 "Invalid default value"
            cursor.execute(
                "ALTER TABLE WaveAssist_Provider ADD COLUMN token_fetch_method VARCHAR(50) NULL"
            )
            cursor.execute(
                "UPDATE WaveAssist_Provider SET token_fetch_method = 'authorization_response' WHERE token_fetch_method IS NULL"
            )
            # No DEFAULT in schema - MySQL 1067 on this server; model default used in Django
            cursor.execute(
                "ALTER TABLE WaveAssist_Provider MODIFY COLUMN token_fetch_method VARCHAR(20) NOT NULL"
            )


def drop_added_columns(apps, schema_editor):
    existing = get_existing_columns(apps, schema_editor)
    with connection.cursor() as cursor:
        for col in ("token_fetch_method", "token_endpoint_auth_method", "extra_token_params", "extra_auth_params"):
            if col in existing:
                cursor.execute("ALTER TABLE WaveAssist_Provider DROP COLUMN %s" % col)


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0054_provider"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="provider",
                    name="extra_auth_params",
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AddField(
                    model_name="provider",
                    name="extra_token_params",
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AddField(
                    model_name="provider",
                    name="token_endpoint_auth_method",
                    field=models.CharField(default="client_secret_basic", max_length=50),
                ),
                migrations.AddField(
                    model_name="provider",
                    name="token_fetch_method",
                    field=models.CharField(default="authorization_response", max_length=20),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_missing_columns, drop_added_columns),
            ],
        ),
    ]
