# Generated by Django 4.2 on 2026-02-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0055_provider_extra_auth_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='default_grant_type',
            field=models.CharField(choices=[('authorization_code', 'Authorization Code'), ('client_credentials', 'Client Credentials'), ('refresh_token', 'Refresh Token')], default='authorization_code', max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='token_endpoint_auth_method',
            field=models.CharField(choices=[('client_secret_basic', 'Client Secret Basic'), ('client_secret_post', 'Client Secret Post'), ('none', 'None')], default='client_secret_basic', max_length=50),
        ),
    ]
