# Generated by Django 4.2 on 2026-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0056_alter_provider_default_grant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='token_fetch_method',
            field=models.CharField(choices=[('authorization_response', 'Authorization Response'), ('code', 'Code')], default='authorization_response', max_length=50),
        ),
    ]
