# Generated by Django 4.2 on 2026-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0057_alter_provider_token_fetch_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credits_check_interval',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='account',
            name='credits_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='credits_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='credits_remaining',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
