# Generated by Django 4.2 on 2026-03-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0059_project_deployed_commit_sha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('dodopayments', 'DoDoPayments')], default='dodopayments', max_length=20)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(default='', max_length=255)),
                ('payload_json', models.TextField(default='{}')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Webhook Event',
                'verbose_name_plural': 'Payment Webhook Events',
                'db_table': 'WaveAssist_PaymentWebhookEvent',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='external_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('credits', 'Credits'), ('subscription_create', 'Subscription Create'), ('subscription_renewal', 'Subscription Renewal')], default='credits', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('dodopayments', 'DoDoPayments')], max_length=20),
        ),
        migrations.CreateModel(
            name='BillingSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('dodopayments', 'DoDoPayments')], default='dodopayments', max_length=20)),
                ('external_subscription_id', models.CharField(max_length=255, unique=True)),
                ('external_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(default='operator', max_length=255)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaveAssistApiApp.account')),
            ],
            options={
                'verbose_name': 'Billing Subscription',
                'verbose_name_plural': 'Billing Subscriptions',
                'db_table': 'WaveAssist_BillingSubscription',
            },
        ),
    ]
