# Generated by Django 4.2 on 2026-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0060_paymentwebhookevent_payment_external_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='open_router_key_hash',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
