# Generated by Django 4.2 on 2026-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaveAssistApiApp', '0062_plan_cleanup_and_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
