# Generated by Django 6.0.5 on 2026-06-14 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0063_project_github_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noderuns",
            name="node_object",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="WaveAssistApiApp.nodes",
            ),
        ),
    ]
