# Generated by Django 6.0.5 on 2026-07-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0065_nodes_chain_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="mcp_token",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="product",
            field=models.CharField(default="waveassist", max_length=32),
        ),
        migrations.AddField(
            model_name="account",
            name="trial_credits_limit",
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name="account",
            name="trial_credits_used",
            field=models.FloatField(default=0),
        ),
    ]
