# Generated by Django 6.0.5 on 2026-07-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WaveAssistApiApp", "0066_account_mcp_token_account_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployments",
            name="consecutive_failures",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UsageLedger",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "project_key",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "run_id",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "node_key",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("source", models.CharField(default="llm", max_length=32)),
                ("amount", models.FloatField(default=0)),
                (
                    "provider",
                    models.CharField(blank=True, default="", max_length=64, null=True),
                ),
                (
                    "model",
                    models.CharField(blank=True, default="", max_length=128, null=True),
                ),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("cost_usd", models.FloatField(blank=True, null=True)),
                ("billable", models.BooleanField(default=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="WaveAssistApiApp.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Ledger Entry",
                "verbose_name_plural": "Usage Ledger",
                "db_table": "WaveAssist_UsageLedger",
                "indexes": [
                    models.Index(
                        fields=["account", "created_at"],
                        name="WaveAssist__account_5f233b_idx",
                    ),
                    models.Index(
                        fields=["run_id"], name="WaveAssist__run_id_97c79e_idx"
                    ),
                ],
            },
        ),
    ]
