"""
Django settings for WaveAssistApi project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Load .env from project root (directory containing manage.py) so runserver sees DODO_*, DB_*, etc.
from dotenv import load_dotenv
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# --- self-hosted / fail-closed config (added by platform sweep) ---
WAVEASSIST_SELF_HOSTED = os.getenv("WAVEASSIST_SELF_HOSTED", "0").strip().lower() in ("1", "true", "yes", "on")

def _require_env(name):
    """Required secret/infra var. No production fallback lives in code, so a missing
    value fails closed instead of silently connecting to WaveAssist production."""
    val = os.getenv(name)
    if val is None or val == "":
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            f"{name} is not set. Set it in this deployment's .env "
            f"(no production default is baked into the code)."
        )
    return val
# --- end sweep helper ---

import posthog
# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _require_env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
IS_DOCKER=True

# Host / CORS / CSRF policy is env-overridable per deployment; defaults preserve the
# hosted-cloud behaviour (unset => exactly as before). A locked-down internet box sets
# WA_ALLOWED_HOSTS to its public hostname(s) PLUS the internal names the app calls
# itself by: 'localhost' (health probe), 'api' (worker/beat/camera/mcp -> http://api:8000),
# and '127.0.0.1'. Set WA_CORS_ORIGINS to the dashboard origin(s) and WA_CORS_ALLOW_ALL=0.
def _csv_env(name):
    return [x.strip() for x in os.getenv(name, "").split(",") if x.strip()]

ALLOWED_HOSTS = _csv_env("WA_ALLOWED_HOSTS") or [
    'wavepredictbackend.us-east-1.elasticbeanstalk.com', '*', 'api.wavepredict.com',
    'app.waveassist.io', 'api.waveassist.io',
]
CORS_ALLOWED_ORIGINS = _csv_env("WA_CORS_ORIGINS") or [
    'http://127.0.0.1:4200', 'https://dashboard.wavepredict.com', 'http://localhost:4200',
    'https://app.waveassist.io', 'https://api.waveassist.io',
]
CSRF_TRUSTED_ORIGINS = _csv_env("WA_CSRF_TRUSTED_ORIGINS") or [
    'https://*.waveassist.io', 'https://*.127.0.0.1', 'http://*.127.0.0.1', 'https://*.wavepredict.com',
]
# Allow-all CORS defaults ON (hosted behaviour); set WA_CORS_ALLOW_ALL=0 to restrict to
# CORS_ALLOWED_ORIGINS on a locked-down deployment.
CORS_ORIGIN_ALLOW_ALL = os.getenv("WA_CORS_ALLOW_ALL", "1").strip().lower() in ("1", "true", "yes", "on")
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'WaveAssistApiApp',
    'django_celery_beat',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    *(['posthog.integrations.django.PosthogContextMiddleware'] if os.getenv('WA_TELEMETRY','on').strip().lower() in ('1','true','yes','on') else []),
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WaveAssistApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WaveAssistApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DB_NAME = os.getenv('DB_NAME', 'waveassistdb')
DB_USER = os.getenv('DB_USER', 'waveassist')
DB_PASSWORD = _require_env('DB_PASSWORD')
DB_HOST = _require_env('DB_HOST')
DB_PORT = os.getenv('DB_PORT', '3306')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'",
        },
    }
}


MONGO_CONNECTION_STRING = _require_env('MONGODB_CONNECTION_STRING')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

FIREBASE_ADMIN_CREDENTIALS = os.getenv('FIREBASE_CREDENTIALS_PATH', os.path.join(BASE_DIR, 'firebase_admin.json'))


POSTHOG_API_KEY = os.getenv('POSTHOG_API_KEY', '')
POSTHOG_HOST = os.getenv('POSTHOG_HOST', 'https://app.posthog.com')

# Configure PostHog Python client (telemetry can be turned off per deployment)
_TELEMETRY_ON = os.getenv('WA_TELEMETRY', 'on').strip().lower() in ('1','true','yes','on')
if _TELEMETRY_ON and POSTHOG_API_KEY:
    posthog.api_key = POSTHOG_API_KEY
    posthog.host = POSTHOG_HOST
else:
    posthog.disabled = True
