WORKER_TOKEN = "REMOVED_CREDENTIAL"
PD_DATA_KEY = 'PDData'
IO_DATA_KEY = 'IODataKey'
DB_NAME = "WaveAssist"
CONNECTION_STRING = "REMOVED_CREDENTIAL"

ZERODHA_API_KEY = 'REMOVED_CREDENTIAL'
ZERODHA_API_SECRET = 'REMOVED_CREDENTIAL'


