WORKER_TOKEN = "REMOVED_CREDENTIAL"
PD_DATA_KEY = 'PDData'
IO_DATA_KEY = 'IODataKey'
DB_NAME = "WaveAssist"
CONNECTION_STRING = "REMOVED_CREDENTIAL"

DATA_KEY = "DATA"
INTEGRATIONS_SUFFIX_KEY = "_integrations"

ZERODHA_API_KEY = "ZERODHA_API_KEY"
ZERODHA_API_SECRET_KEY = "ZERODHA_API_SECRET"
ZERODHA_ACCESS_TOKEN_KEY = "ZERODHA_ACCESS_TOKEN_KEY"


ZERODHA_API_KEY_VALUE = "REMOVED_CREDENTIAL"
ZERODHA_API_SECRET_KEY_VALUE = "REMOVED_CREDENTIAL"


AWSS3_ACCESS_KEY = "AWSS3_ACCESS_KEY"
AWSS3_SECRET = "AWSS3_SECRET"


AWSS3_ACCESS_KEY_VALUE = "REMOVED_CREDENTIAL"
AWSS3_SECRET_KEY_VALUE = "REMOVED_CREDENTIAL"
